version: '3.9'
services:
  rabbit:
    image: rabbitmq:3.13.1
    volumes:
      - ./data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin